### ISSUE TITLE
.vue file not support

### ISSUE THREAD

**Issue by chuanxd** [joelday/vscode-docthis#100]
`.vue` file is not support.
```
<script>
  // javascript code
  const foo = 'bar'
</script>
```

**Comment by joelday** [comment]
Fixed in 0.3.11. Thank you!

**Comment by klarkc** [comment]
Still not working: `Sorry! 'Document This' wasn't able to produce documentation at the current position.`

.vue file:
```
<template lang="html">
 <div></div>
</template>

<script>
const foo = 'bar'

export default {}
</script>

<style lang="css" scoped>
</style>
```
